{"status":"OK","result":{"originalLocale":"en","allowViewHistory":false,"creationTimeSeconds":1430858084,"rating":0,"authorHandle":"crisig","modificationTimeSeconds":1430858084,"id":17738,"title":"\u003cp\u003eReceiving Runtime error during submission Python 2.7\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eIn my computer the code works perfect , I\u0027ve tried in several cases and also manually . My problem is that when I go I get a \u0026quot; Runtime Error\u0026quot; , and not that you should . Could you help me?\u003c/p\u003e\u003cp\u003e\u003ca href\u003d\"http://pastebin.com/p09D6NGu\"\u003ehttp://pastebin.com/p09D6NGu\u003c/a\u003e\u003c/p\u003e\u003cp\u003e\u003ca href\u003d\"/contest/230/problem/A\" title\u003d\"Codeforces Round 142 (Div. 2)\"\u003e230A - Dragons\u003c/a\u003e \u003ca href\u003d\"/contest/230/submission/11008708\" title\u003d\"Submission 11008708 by crisig\"\u003e11008708\u003c/a\u003e\u003c/p\u003e\u003c/div\u003e","tags":["help","runtime error","python 2","230a"]}}