{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1470652242,"rating":181,"authorHandle":"Na2a","modificationTimeSeconds":1470655132,"id":46466,"title":"\u003cp\u003eios_base::sync_with_stdio(0) receives runtime error! \u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eHello, Codeforces!\u003c/p\u003e\u003cp\u003eYesterday, in CF Round 366 my friend \u003ca class\u003d\"rated-user user-blue\" href\u003d\"/profile/Birjik\" title\u003d\"Expert Birjik\"\u003eBirjik\u003c/a\u003e encountered a strange problem. His correct code was receiving Runtime Error in sample case.\u003c/p\u003e\u003cp\u003eTake a look at these codes:\u003cbr /\u003e\u003ca href\u003d\"//codeforces.com/contest/705/submission/19695431\"\u003eRuntime error\u003c/a\u003e\u003cbr /\u003e\u003ca href\u003d\"//codeforces.com/contest/705/submission/19725623\"\u003eAccepted\u003c/a\u003e\u003c/p\u003e\u003cp\u003eAs you can notice, one code has these lines:\u003c/p\u003e \u003cpre\u003e\u003ccode\u003eios_base::sync_with_stdio(0);\ncin.tie(0);\n\u003c/code\u003e\u003c/pre\u003e\u003cp\u003eStrange, isn\u0027t it?\u003cbr /\u003eAs I have understood, this happens because of an array called read.\u003cbr /\u003eRenaming that array solves this problem. \u003c/p\u003e\u003cp\u003eLong story short, using ios_base / cin.tie receives runtime error if we have a variable named read in our code.\u003cbr /\u003eBe careful!\u003c/p\u003e\u003c/div\u003e","tags":["read","ios_base","cin.tie","runtime"]}}