{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1494559046,"rating":0,"authorHandle":"GODOF_Shinobi","modificationTimeSeconds":1494559046,"id":51935,"title":"\u003cp\u003ePlayrix Codescapes Cup Problem B: T-shirt buying\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eThis post is regarding yesterday\u0027s problem B. \u003c/p\u003e\u003cp\u003eHere are two solutions \u003ca href\u003d\"/contest/799/submission/27045354\" title\u003d\"Submission 27045354 by GODOF_Shinobi\"\u003e27045354\u003c/a\u003e and \u003ca href\u003d\"/contest/799/submission/27019672\" title\u003d\"Submission 27019672 by GODOF_Shinobi\"\u003e27019672\u003c/a\u003e although being similar , one of the two solutions passed and the other had a TLE on Case 39. \u003c/p\u003e\u003cp\u003eI know when we try to find and delete an element which is not present in set using \u003cstrong\u003eset.erase(set.find(x))\u003c/strong\u003e ,then it gives an exception as find returns an iterator that points at the end of the set.\u003c/p\u003e\u003cp\u003eMy doubt is does this happen even if I use \u003cstrong\u003eset.erase(x)\u003c/strong\u003e, or was this ambiguous nature?\u003c/p\u003e\u003cp\u003eAny help would be appreciated.\u003c/p\u003e\u003c/div\u003e","tags":["t-shirt buying"]}}