{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1440166558,"rating":0,"authorHandle":"ananth94","modificationTimeSeconds":1440166792,"id":19895,"title":"\u003cp\u003eUnexpected runtime error on testcase [SOLVED].\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eI\u0027ve been trying to solve this problem â€” \u003ca href\u003d\"/contest/385/problem/C\" title\u003d\"Codeforces Round 226 (Div. 2)\"\u003e385C - Bear and Prime Numbers\u003c/a\u003e , Bear and Prime Numbers. My solution gives a completely expected runtime error on Testcase#4. Can someone please explain to me as to why this is happening? \u003c/p\u003e\u003cp\u003eMy solution: \u003ca href\u003d\"//codeforces.com/contest/385/submission/12629174\"\u003ehttp://codeforces.com/contest/385/submission/12629174\u003c/a\u003e\u003c/p\u003e\u003cp\u003eAny help would be greatly appreciated.\u003c/p\u003e\u003cp\u003eThanks in advance.\u003c/p\u003e\u003cp\u003eEDIT: Solved. I had not taken into consideration that even l could be greater than 10000000.\u003c/p\u003e\u003c/div\u003e","tags":["c++11","runtime error","dynamic programming","practice"]}}