{"status":"OK","result":{"originalLocale":"ru","allowViewHistory":true,"creationTimeSeconds":1520718211,"rating":0,"authorHandle":"Schullz","modificationTimeSeconds":1520718361,"id":58294,"title":"\u003cp\u003eIDLENESS_LIMIT_EXCEEDED Ð² Python 3 (PyPy)\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eI have sent a solution in PyPy 3 and got IDLENESS_LIMIT_EXCEEDED on test #2 \u003ca href\u003d\"//codeforces.com/contest/950/submission/36179906\"\u003ehttp://codeforces.com/contest/950/submission/36179906\u003c/a\u003e\u003c/p\u003e\u003cp\u003eThen I deleted or added some empty strings in my solution (because Codeforces forbids to send identical code) and got Accepted. \u003ca href\u003d\"//codeforces.com/contest/950/submission/36180011\"\u003ehttp://codeforces.com/contest/950/submission/36180011\u003c/a\u003e\u003c/p\u003e\u003cp\u003eExplain me, please, what happens?\u003c/p\u003e\u003c/div\u003e","tags":[]}}