{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1487433428,"rating":1,"authorHandle":"T1mka","modificationTimeSeconds":1487433428,"id":50504,"title":"\u003cp\u003eUndefined Behavior of C++\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eSee this submission -\u0026gt; \u003ca href\u003d\"//codeforces.com/contest/767/submission/24782701\"\u003eClick\u003c/a\u003e.\u003c/p\u003e\u003cp\u003eAs you see, I got a runtime error because of \u0026quot;assert\u0026quot; function that I added while debugging my code. My array S is an array of pairs where second value is an index from (1..m). I can not understrand why my code is getting a runtime error. \u0026quot;assert(s[i].second \u0026lt;\u003d m)\u0026quot; should be fine but it leads to an error. Why?\u003c/p\u003e\u003c/div\u003e","tags":[]}}