{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1468778562,"rating":-15,"authorHandle":"arasmus","modificationTimeSeconds":1468781402,"id":46094,"title":"\u003cp\u003eUnexpected Error\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003e\u003ca href\u003d\"/contest/354/submission/19194587\" title\u003d\"Submission 19194587 by arasmus\"\u003e19194587\u003c/a\u003e\u003cbr /\u003e The code gives runtime error .\u003cbr /\u003e  the line \u003ccode\u003e mod1[X%10].push_back({X/10,f,s}) \u003c/code\u003e is causing the problem , if u comment it out everything runs fine \u003cbr /\u003e\u003cb\u003eHow can this simple push_back() cause a RE (array index of mod1 vector are in bound)\u003c/b\u003e\u003c/p\u003e\u003cpre\u003e  for(int s\u003d0;s\u0026lt;\u003d6;s++)\u003cbr /\u003e  for(int f \u003d 0; (f+s)\u0026lt;\u003d6;f++){\u003cbr /\u003e  int X \u003d s*7 + f*4;\u003cbr /\u003e  mod1[X%10].push_back({X/10,f,s});\u003cbr /\u003e  }\u003cbr /\u003e  \u003c/pre\u003e\u003c/div\u003e","tags":[]}}