{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1464687797,"rating":6,"authorHandle":"KadiyalaSaiManoj","modificationTimeSeconds":1464687903,"id":45135,"title":"\u003cp\u003ePython Headache: Problems with Recursion Limit\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eIt seems python has a low recursion Limit creating problems like runtime error. I have faced this problem in the following questions. It seems we have to use sys.setrecursionlimit().\u003c/p\u003e\u003cp\u003e\u003ca href\u003d\"/contest/667/problem/C\" title\u003d\"Codeforces Round 349 (Div. 2)\"\u003e667C - Ребляндская лингвистика\u003c/a\u003e without using sys.setrecursionlimit \u003ca href\u003d\"/contest/667/submission/18166330\" title\u003d\"Посылка 18166330 от KadiyalaSaiManoj\"\u003e18166330\u003c/a\u003e.\u003c/p\u003e\u003cp\u003epassed \u003ca href\u003d\"/contest/667/submission/18165938\" title\u003d\"Посылка 18165938 от KadiyalaSaiManoj\"\u003e18165938\u003c/a\u003e.\u003c/p\u003e\u003cp\u003ebut this is also not working in some cases\u003c/p\u003e\u003cp\u003e\u003ca href\u003d\"/contest/445/problem/A\" title\u003d\"Codeforces Round 254 (Div. 2)\"\u003e445A - DZY любит шахматную доску\u003c/a\u003e (python3 runtime-error with limit set) \u003ca href\u003d\"/contest/445/submission/18166280\" title\u003d\"Посылка 18166280 от KadiyalaSaiManoj\"\u003e18166280\u003c/a\u003e.\u003c/p\u003e\u003cp\u003e(python2 same code) \u003ca href\u003d\"/contest/445/submission/18166286\" title\u003d\"Посылка 18166286 от KadiyalaSaiManoj\"\u003e18166286\u003c/a\u003e\u003c/p\u003e\u003cp\u003eCan anyone shed some light over this topic\u003c/p\u003e\u003cp\u003edid anyone face similar problems with python and why python3 is failing and python2 is passing with eventhough i set recursionlimit explicilty.\u003c/p\u003e\u003cp\u003eThanks\u003c/p\u003e\u003c/div\u003e","tags":[]}}